### ISSUE TITLE
Typo on the docs?

### ISSUE THREAD

**Issue by lpasz** [vincent178/nvim-github-linker#2]
Awesome plugin, It’s really useful for me in my day to day.

When configuring it I found a mistake. Not sure if it’s related to the lazy-vim or it’s just a typo

My config is 
```lua
return {
  "vincent178/nvim-github-linker",
  config = function()
    require("nvim-github-linker").setup({
      mappings = true,
      default_remote = "origin",
      copy_to_clipboard = true,
    })
  end,
}
```

not sure if you renamed the repo and missed this 

`neovim` -> `nvim`

```lua
use {
    "vincent178/neovim-github-linker",
    config = function()
        require("neovim-github-linker").setup()
    end,
}
```

**Comment by vincent178** [comment]
hi @lpasz , this should be fixed c88516ed064e74529e452b522e0f60cb70aa2a1f , thanks for mentioning this.
